### ISSUE TITLE
Add and remove multiple roles

### ISSUE THREAD

**Issue by martygrant** [martygrant/uwsgamedevbot#29]
Using the !role command to add a role to a user profile, allow the user to add or remove more than one role at a time. The API function add and remove also takes a struct of roles so the functionality would be facilitated well. E.g:

!role 1st year | computer games development

The and operator could be of any style, comma separated, |, and, &...

**Comment by Medallyon** [comment]
Implemented in fc5b97a7984ea0f6b3ab0a0f3a472ccabf1e823c.
