### ISSUE TITLE
Image/gif searching

### ISSUE THREAD

**Issue by martygrant** [martygrant/uwsgamedevbot#6]
Search for and broadcast images and gifs. Example:

!image dog
!gif cat

**Comment by Medallyon** [comment]
Discord has gif search functionality built into the discord client in the form of 2 chat commands: `/giphy` and `/tenor`. I guess it's kind of superfluous to implement this command, but can still be implemented for demo purposes.

Either way, bead719abe8a49be43a05a6648d2d897a271140a seems to have implemented this already. Should this issue be closed?

**Comment by martygrant** [comment]
Sure. I forgot about the built in gif option. I'll just remove the command so there are less dependencies. Thanks!
